src/Entity/User.php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity(fields: ['email'], message: 'Cet email est déjà utilisé !')]
/**
 * @ORM\Entity
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(length: 255)]
    private ?string $prenom = null;

    #[ORM\OneToMany(mappedBy: 'users', targetEntity: Commentaire::class)]
    private Collection $coms;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Abonnement $abonnement = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Role $role = null;

    #[ORM\Column(type: 'boolean')]
    private ?bool $is_verified = false;

    #[ORM\Column(type: 'string', length: 100, nullable: true)]
    private $resetToken;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable: true)]
    private ?DateTimeInterface $dateFinAbonnement = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Adresse = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Ville = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $Tel = null;

    #[ORM\ManyToMany(targetEntity: Video::class, inversedBy: 'users')]
    private Collection $videoPref;

    #[ORM\ManyToMany(targetEntity: Categorie::class, inversedBy: 'users')]
    private Collection $categoriePref;

    public function __construct()
    {
        $this->coms = new ArrayCollection();
        $this->videoPref = new ArrayCollection();
        $this->categoriePref = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getIsVerified(): ?bool
    {
        return $this->is_verified;
    }

    public function setIsVerified(bool $is_verified): self
    {
        $this->is_verified = $is_verified;

        return $this;
    }

    /**
     * @return Collection<int, commentaire>
     */
    public function getComs(): Collection
    {
        return $this->coms;
    }

    public function addCom(commentaire $com): self
    {
        if (!$this->coms->contains($com)) {
            $this->coms->add($com);
            $com->setUsers($this);
        }

        return $this;
    }

    public function removeCom(commentaire $com): self
    {
        if ($this->coms->removeElement($com)) {
            // set the owning side to null (unless already changed)
            if ($com->getUsers() === $this) {
                $com->setUsers(null);
            }
        }

        return $this;
    }

    public function getAbonnement(): ?Abonnement
    {
        return $this->abonnement;
    }

    public function setAbonnement(?Abonnement $abonnement): self
    {
        $this->abonnement = $abonnement;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getResetToken(): ?string
    {
        return $this->resetToken;
    }

    public function setResetToken(?string $resetToken): self
    {
        $this->resetToken = $resetToken;

        return $this;
    }

    public function getDateFinAbonnement(): ?\DateTimeInterface
    {
        return $this->dateFinAbonnement;
    }

    public function setDateFinAbonnement(?\DateTimeInterface $dateFinAbonnement): self
    {
        $this->dateFinAbonnement = $dateFinAbonnement;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->Adresse;
    }

    public function setAdresse(?string $Adresse): self
    {
        $this->Adresse = $Adresse;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->Ville;
    }

    public function setVille(?string $Ville): self
    {
        $this->Ville = $Ville;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideoPref(): Collection
    {
        return $this->videoPref;
    }

    public function addVideoPref(Video $videoPref): self
    {
        if (!$this->videoPref->contains($videoPref)) {
            $this->videoPref->add($videoPref);
        }

        return $this;
    }

    public function removeVideoPref(Video $videoPref): self
    {
        $this->videoPref->removeElement($videoPref);

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategoriePref(): Collection
    {
        return $this->categoriePref;
    }

    public function addCategoriePref(Categorie $categoriePref): self
    {
        if (!$this->categoriePref->contains($categoriePref)) {
            $this->categoriePref->add($categoriePref);
        }

        return $this;
    }

    public function removeCategoriePref(Categorie $categoriePref): self
    {
        $this->categoriePref->removeElement($categoriePref);

        return $this;
    }
    
}

templates/base.html.twig
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, width=device-width"/>
  <meta name="viewport" content="maximum-scale=1.0, minimum-scale=1.0"/>
  <meta name="viewport" content="width=800" />


  <title>Portail</title>
  <link rel="stylesheet" href="/css/bootstrap.min.css">
  <link href="https://vjs.zencdn.net/8.0.4/video-js.css" rel="stylesheet" />
  <script src="https://vjs.zencdn.net/8.0.4/video.min.js"></script>
  {# <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script> #}
  	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.min.js"></script>
  {# <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.min.js"> #}
<script src="https://cdn.jsdelivr.net/npm/chart.js@3.6.0"></script>
<script src="https://cdn.jsdelivr.net/npm/chartjs-plugin-datalabels@2.0.0"></script>
<script src="https://cdn.jsdelivr.net/npm/chart.piecelabel.js"></script>

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css" rel="stylesheet">

  <link rel="stylesheet" href="/css/footer.css"> 
  <link rel="stylesheet" href="/css/navbar.css"> 
  <link rel="stylesheet" href="/css/styleIndex.css"> 
  <link rel="stylesheet" href="{{ asset('css/navbar.css') }}">
  <link rel="stylesheet" href="{{ asset('css/styleIndex.css') }}">
  <link rel="stylesheet" href="{{ asset('css/footer.css') }}">

{% block stylesheets %}
{% endblock %}


</head>
<body style="padding-right: 0px;overflow: overlay;" data-bs-padding-right="0px">

{% include 'partials/header.html.twig' %}


{% block header %}
{% endblock %}
{% include "partials/_flash.html.twig" %}
{% if app.user and app.user.isVerified == false %}
			<div style="margin-top:80px" class="alert alert-warning alert-dismissible" role="alert">
				<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
				<div class="alert-message">
					<strong>Votre compte n'est pas activé</strong>, 
          <a href="{{ path('resend_verif') }}" style="color: blue;">renvoyer le lien d'activation</a> 
				</div>
			</div>
		{% endif %}
{% include "partials/_flash.html.twig" %}
{% block body %}
{% endblock %}


{% block footer %}
  {% include 'partials/footer.html.twig' %}
{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>

</body>
{% block javascripts %}
  {# javascripts #}

{% endblock %}
</html>